apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent-dev
spec:
  license:
    globalLicense: true
  replicas: 1
  image:
    application: 000451337248.dkr.ecr.us-gov-east-1.amazonaws.com/confluentinc/cp-schema-registry:7.6.1
    init: 000451337248.dkr.ecr.us-gov-east-1.amazonaws.com/confluentinc/confluent-init-container:2.8.2
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits: {}
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  listeners:
    #external:
      #authentication:
      #  type: mtls
     #   principalMappingRules:
     #     - RULE:^.*CN=([a-zA-Z0-9.]*).*$/$1/L 
      #tls:
       # enabled: true         
  tls:
    secretRef: sr-tls
  license:
    globalLicense: true
  authentication:
    type: mtls  
 # authorization:
 #   type: rbac          
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-dev.svc.cluster.local:9092    
      authentication: 
        type: mtls
  #  mds:
   #   endpoint: https://kafka.confluent-dev.svc.cluster.local:8090
    #  tokenKeyPair:
     #   secretRef: kafka-tls
      #authentication:
       # type: bearer
        #  bearer:
         # secretRef: sr-tls        
      tls:
        enabled: true      
      